### ISSUE TITLE
New release (20.2) has a typing issue

### ISSUE THREAD

**Issue by sobolevn** [hynek/structlog#290]
My CI fails for a new `structlog` release: https://github.com/wemake-services/wemake-django-template/pull/1418/checks?check_run_id=1632259635#step:7:861

Here's what happens:

```
mypy manage.py server tests/test_apps/test_main/test_models/test_migrations/test_blog_post_migrations.py tests/test_apps/test_main/test_models/test_blog_post_model.py tests/test_apps/test_main/test_views/test_index_view.py tests/conftest.py tests/test_server/test_urls.py
server/settings/components/logging.py:73: error: Argument "context_class" to "configure" has incompatible type "Type[MutableMapping[str, Any]]"; expected "Union[Type[Dict[str, Any]], Type[Dict[Any, Any]], None]"
Found 1 error in 1 file (checked 28 source files)
```

Here's the source code which works correctly with `20.1`: https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/server/settings/components/logging.py#L73

P.S. Happy New Year! 🎄

**Comment by hynek** [comment]
Aw crap, does wrap_dict return the wrong type? Gotta expand typing-examples I guess 😒.

Meanwhile, may I recommend stopping to use wrap_dict and look into the new threadlocal primitives that allow to separate what you keep in threadlocal and what not? I think they're highly superior!

**Comment by hynek** [comment]
Fixed and used your example as a regression test in the typing example. Happy new year to you too!

**Comment by mazzi** [comment]
When do you plan to release this fix @hynek ?
Thanks a lot! 😄

**Comment by hynek** [comment]
I'm sorry, but that doesn't warrant an emergency release…just add a `# typing: ignore` next to it for now. I want to work on all the stdlib logging meta data (#253, #209 and maybe some more) next once I've finished my current work project. I will release immediately after because it's super vexing to me.
