### ISSUE TITLE
AsyncBoundLogger is not compatible with Python 3.6

### ISSUE THREAD

**Issue by guhcampos** [hynek/structlog#328]
Trying to create an `AsyncBoundLogger` on Python 3.6 fails with

```
/.venv/lib/python3.6/site-packages/structlog/stdlib.py", line 416, in __init__
    self._loop = asyncio.get_running_loop()
AttributeError: module 'asyncio' has no attribute 'get_running_loop'
```

Which makes sense since this particular function was introduced in 3.7.

This seems to be the only feature which won't work in 3.6, since I've been using structlog without any issues lately. The only reason I'm stuck with 3.6 is `pypy`, which has recently moved to 3.7, so this may soon become a non-issue for most anyone in the same situation.

Still, it might be worth adding a note to the docs or maybe a more specific error message?

**Comment by hynek** [comment]
[The docs](https://www.structlog.org/en/stable/api.html#structlog.stdlib.AsyncBoundLogger) _do_ say

> Only available for Python 3.7 and later.

tho?

> This seems to be the only feature which won't work in 3.6, since I've been using structlog without any issues lately.

I'm afraid that's not true. The main reason why that logger is 3.7+ is the baked-in support for contextvars.

---

That's no an unsolvable problem though! Just copy and paste AsyncBoundLogger from https://github.com/hynek/structlog/blob/main/src/structlog/stdlib.py and remove the parts that you can't use.

**Comment by guhcampos** [comment]
> The docs do say

Whoa, I completely-utterly-properly missed that by leagues. Sorry!
