### ISSUE TITLE
structlog 21.3.0 fails with `python -OO`

### ISSUE THREAD

**Issue by mha-kialo** [hynek/structlog#374]
`__doc__.strip()` in [`structlog/__init__.py`, line 48](https://github.com/hynek/structlog/blob/21.3.0/src/structlog/__init__.py#L48) (introduced with 5e6ea9c04e070f7ef0106ff1256c58ef54c03686) fails with 
> AttributeError: 'NoneType' object has no attribute 'strip'

when used with `python -OO`, which discards docstrings.

**Comment by mha-kialo** [comment]
As a fix, I'd just duplicate the string and set
```py
__description__ = "Structured Logging for Python"
```
It's not trivial to cover this with conventional tests, as `python -O` already removes `assert` statements.
But if you wish, I could try to contribute a separate job within `.github/workflows/main.yml`.

**Comment by hynek** [comment]
This has already been fixed in #373. I’m only waiting for #371 and will release 21.4.

**Comment by mha-kialo** [comment]
Oh, never mind: I didn't see that PR. Thanks!

**Comment by hynek** [comment]
FYI 21.4 is on PyPI
